# Generated by Django 4.0.3 on 2022-04-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
