# Generated by Django 4.0.3 on 2022-04-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_sem',
            field=models.IntegerField(choices=[(3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)]),
        ),
    ]
