# Generated by Django 4.0.3 on 2022-04-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_total_attendance_percentage'),
        ('course', '0003_alter_course_course_sem'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrolled_students',
            field=models.ManyToManyField(to='student.student'),
        ),
    ]
