# Generated by Django 4.0.3 on 2022-04-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_remove_faculty_course_taught'),
        ('student', '0002_alter_student_total_attendance_percentage'),
        ('course', '0004_course_enrolled_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='taught_by',
            field=models.ManyToManyField(blank=True, to='faculty.faculty'),
        ),
        migrations.AlterField(
            model_name='course',
            name='enrolled_students',
            field=models.ManyToManyField(blank=True, to='student.student'),
        ),
    ]
