# Generated by Django 4.0.3 on 2022-04-15 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='teacher_id',
            new_name='user_id',
        ),
    ]
