# Generated by Django 4.0.3 on 2022-04-23 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_course_id'),
        ('faculty', '0002_rename_teacher_id_faculty_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='course_taught',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.course'),
        ),
    ]
