# Generated by Django 4.0.3 on 2022-04-24 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_faculty_course_taught'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='course_taught',
        ),
    ]
