# Generated by Django 4.0.2 on 2022-02-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='course_id',
            new_name='course',
        ),
        migrations.AddField(
            model_name='student',
            name='percentage_attendance',
            field=models.FloatField(null=True),
        ),
    ]
