# Generated by Django 4.0.2 on 2022-02-23 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_course_id_attendance_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='student_roll_no',
            new_name='student',
        ),
    ]
