# Generated by Django 4.0.2 on 2022-02-23 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_student_roll_no_attendance_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='student',
            new_name='student_roll_no',
        ),
    ]
