# Generated by Django 4.0.2 on 2022-03-02 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_student_attendance_student_roll_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='student_roll_no',
            new_name='student',
        ),
    ]
