# Generated by Django 4.0.2 on 2022-03-02 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_student_roll_no_attendance_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='percentage_attendance',
            new_name='total_attendance_percentage',
        ),
    ]
