# Generated by Django 4.0.2 on 2022-03-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_course_taught_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='lec_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
