# Generated by Django 4.0.2 on 2022-03-08 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_student_email_alter_student_roll_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lec_Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lec_no', models.IntegerField()),
                ('students_present', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
            ],
        ),
    ]
