# Generated by Django 4.0.2 on 2022-03-09 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_attendance_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lec_stat',
            old_name='course_id',
            new_name='course',
        ),
    ]
