# Generated by Django 4.0.2 on 2022-03-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_course_id_lec_stat_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='student_status',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
