# Generated by Django 4.0.2 on 2022-03-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_attendance_student_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lec_stat',
            name='attendance_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(max_length=64),
        ),
    ]
