# Generated by Django 4.0.3 on 2022-03-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='type',
            field=models.CharField(default='user', max_length=10),
        ),
    ]
