# Generated by Django 4.0.3 on 2022-03-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_teacher_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='type',
            field=models.CharField(default='teacher', max_length=10),
        ),
    ]
