# Generated by Django 4.0.3 on 2022-04-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_no', models.IntegerField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=20)),
                ('l_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('total_attendance_percentage', models.FloatField(null=True)),
            ],
        ),
    ]
